### ISSUE TITLE
[Suggestion] Export Block Display Entities

### ISSUE THREAD

**Issue by ANONIM4IK3327** [BramStoutProductions/MiEx#136]
There are entities like Block display, I've seen them used on some maps, but exporters cannot export them.

so is it possible to add the export of block display entities to miex? (website where you can download bd entities of varying complexity: [click](https://block-display.com/editor/))

**Comment by BramStout** [comment]
I have released a new experimental build that adds in support for display entities.

You can find the build here: https://github.com/BramStoutProductions/MiEx/releases/tag/v2.0.0.experimental-5

**Comment by ANONIM4IK3327** [comment]
> I have released a new experimental build that adds in support for display entities.
> 
> You can find the build here: https://github.com/BramStoutProductions/MiEx/releases/tag/v2.0.0.experimental-5 

I tested the update and there are some problems. the objects in the world look fine, but when I imported them into blender, are they rotated? I can't say for sure, but here are some screenshots from the editor and blender.
![Screenshot_20250418_012536.png](https://github.com/user-attachments/assets/7c89de1e-968e-4d6a-9c54-4b1c96baac58)

https://block-display.com/bd/1247/

![Screenshot_20250418_013551.png](https://github.com/user-attachments/assets/cb5f27c4-1907-4616-90a5-f9d4224f9d35)

![Screenshot_20250418_012855.png](https://github.com/user-attachments/assets/194c7083-1ff1-4297-a3c5-acf3c53d8ccc)

https://block-display.com/bd/10929/

![Screenshot_20250418_014828_Chrome.png](https://github.com/user-attachments/assets/54ee9ba5-48db-4b70-a67c-359dd87384ec)

**Comment by BramStout** [comment]
Turns out that item display entities needed to be rotated 180 degrees, to match Minecraft. Not sure why that's the case, since block display entities don't need that rotation, but regardless I have fixed it.

I've updated the files in the repository and MiEx nowadays will check the repository for updated built in files and automatically download it. So, the next time that you launch MiEx it should automatically download the fix and display entities should export out correctly now

**Comment by 4nyNoob** [comment]
it appears that this implementation still lacks custom_model_data support
and all the transforms except location are already applied to the item display entities (i guess this might be related to the blender add-on)

even tough it's still missing some features this is already a huge help to me <3 tysm for this amazing tool

**Comment by BramStout** [comment]
> it appears that this implementation still lacks custom_model_data support and all the transforms except location are already applied to the item display entities (i guess this might be related to the blender add-on)
> 
> even tough it's still missing some features this is already a huge help to me <3 tysm for this amazing tool

In theory custom_model_data should be supported, although I haven't had the time to fully test it. Could you provide me with some item display entities (either a summon command or a world containing them) that don't show up as intended? Then I have something specific to look into, to figure out what's causing it to not work properly.

The transformation property is indeed baked onto the model, which includes translation. Entity position and rotation are put into the translation and rotation attributes on the group for the entity. This is intended, since it makes it easy to ensure that the display entities are exported out correctly

**Comment by 4nyNoob** [comment]
I've made this: [RP-testing.zip](https://github.com/user-attachments/files/19855839/RP-testing.zip)  which is a world with a resource pack built in, which is representative of what I'm dealing with in a general way

a bunch of custom models inside a single minecraft item, some of them are just using the texture color and some of them are using tint colors, my models aren't top notch but it's complex enough to show that this is definitely a custom model and to be tinted

**Comment by BramStout** [comment]
I have just released a new experimental version of MiEx that fixes some issues regarding Display Entities. Could you check to see if the issues are now solved, or if they are still there? https://github.com/BramStoutProductions/MiEx/releases/tag/v2.0.0.experimental-6

**Comment by 4nyNoob** [comment]
i was anxiously waiting for an update on this and I'm very happy to announce that it works :D
![Image](https://github.com/user-attachments/assets/d8ed2026-e8ba-47e4-a52a-1a60a16f6f95)
Thank you for the work on this issue, this will be amazing for my future projects, if there's anywhere where i can donate to the project to I'd like to know (even tough my currency isn't worth much 😅)

**Comment by BramStout** [comment]
> i was anxiously waiting for an update on this and I'm very happy to announce that it works :D ![Image](https://github.com/user-attachments/assets/d8ed2026-e8ba-47e4-a52a-1a60a16f6f95) Thank you for the work on this issue, this will be amazing for my future projects, if there's anywhere where i can donate to the project to I'd like to know (even tough my currency isn't worth much 😅)

Great to hear that it works now!

I don't accept donations for MiEx. It's not needed and most people need their money more than I do. If you'd like to support this project, then the best way would be to share it with others!
